# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


En el ejercicio 1 creé un array de 12 ceros usando np.zeros()

In [4]:
import numpy as np

ejercicio1=np.zeros((12,), dtype=int)

print(ejercicio1)

[0 0 0 0 0 0 0 0 0 0 0 0]


En el ejercicio 2 creé un array a mano usando np.array([])

In [5]:
import numpy as np

ejercicio2=np.array([0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0])

print(ejercicio2)

[ 0  0  0  0  0 10  0  0  0  0  0]


Ejercicio 3: Crear un arreglo que tenga numeros del 10 al 49.

In [ ]:
import numpy as np

np.arange(10,50,1) #arange goes start,stop,step


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8


In [ ]:
import numpy as np

ej4 = np.array([np.arange(0,3,1), np.arange(3,6,1), np.arange(6,9,1)])

print(ej4.ndim)

2


Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza


In [65]:
import numpy as np

array = np.random.randint(0,100,100) #low,high,size

media = np.mean(array)

varianza = np.var(array)

print("Array de 100 números del 0 al 100: ", array)
print("Media: ", media)
print("Varianza: ", varianza)

Array de 100 números del 0 al 100:  [76 75 16 26 57 13 62 50 99 19 61 34 27 86 25 47 88 65 85 39 10  4 51 73
 24 29 18 14 78 75 34 42 84 53 44 48 39  6 70 28 92 13 25  2 90 91 12 25
 10 88 89 34  7 62 21 78  3 75 43 42 87 90 37 27  4 47  3 68 15 57 29 73
 37  7 49 60 58 44 38 60 73 42 49 20 59 37  8 62 29 48 83  2 80 11 23 77
 29 82 16 51]
Media:  45.47
Varianza:  751.3490999999999


Ejercicio 6: Calcular la media de un arreglo usando np.sum

In [58]:
array6 = np.random.randint(0,100,100)

suma = np.sum(array6) #suma de todos los elementos de array6

cantidad_de_elementos = len(array6) 

media = suma / cantidad_de_elementos


print(array6)
print(suma)
print(cantidad_de_elementos)
print(media)

[14 49 93 51  2 68 89 44 49 79 56 79 65 55 37 19 37 51 34 18 99 87 71 67
 73 44 41  4 41 47 44 30 12 45  7 10 72 87 87 48 45 47 25 85 12 95 11 42
 86 68 75 14 17 97 66 23  8 39 84 41 92 20 75 96 42 17 35 23 52 17 64 40
 96 47 93 99 44 67 67 97 98 82 59 34 51 39  7 99 41  9 19 99 42 42 17 17
 60 53 12 55]
5103
100
51.03


Ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean


In [67]:
array7 = np.random.randint(0,100,100) 

media = np.mean(array7)

suma_cuadrados_diferencias = np.sum((array7 - media)**2)

varianza_a_mano = suma_cuadrados_diferencias / len(array7)

varianza_numpy = np.var(array7)

print(array7)
print("Media: ", media)
print("Suma diferencias de cuadrados: ", suma_cuadrados_diferencias)
print("Varianza hecha a mano: ", varianza_a_mano)
print("Varianza hecha con Numpy: ", varianza_numpy)

[ 8 85 59 23  6  2 36 95 23 71 59 23 47 95 17 81 13 78 24 16 73 34 43  4
 19 26 81 72 71 91 90 23 39 19 95 33 21 37 89 44 41 74 15 87 19 80 85 14
 25 40  3 24  7 95 47 58 52 67 16  7 46 31 15 72 29 59 73 64 16 57 57  5
 83 69 11 58 79 76 64 96 71 71 73 70 57 76 92  3 65 37 59 61 88 76 37 50
 96 23 53 28]
Media:  49.67
Suma diferencias de cuadrados:  81340.11
Varianza hecha a mano:  813.4011
Varianza hecha con Numpy:  813.4011


Ejercicio 8: Crear un array de números aleatorios usando np.random.randn.

In [7]:
import numpy as np

np.random.randn(1,4)

array([[-1.51315315,  0.7688828 , -0.15695816,  0.43418102]])